### ISSUE TITLE
Use official cmake modules from TBB instead of maintaining own CMakeList

### ISSUE THREAD

**Issue by anton-malakhov** [conda-forge/tbb-feedstock#3]
There is a big risk that this recipe does not follow the official way to build TBB. In the case when the structure of TBB sources changes or compiler flags changes in its own build system, it will not be noticed and reflected by this recipe and will (eventually - I'm sure) cause severe incompatibility issues. It is ok to have cmake recipe as an alternative for these who worship cmake, but this repository and the tbb name implies that it is the main approach for conda-forge users to build TBB, and it is inherently broken.

**Comment by jakirkham** [comment]
So, I don't know if you looked at the build scripts, but this is only used for the Windows build. Without CMake, unfortunately, there is no real way to build TBB for VS on Windows. What would you suggest to do instead?

**Comment by antalmal** [comment]
What do you mean by "real way"? I was so surprised by this statement that decided to conduct an experiment. I downloaded recent TBB sources, googled "gnu make for windows 64 bit" and downloaded GNU "make" program from the very first page suggested (http://gnuwin32.sourceforge.net/packages/make.htm), unpacked, opened VS2015 x64 command line and ran "make" in the tbb directory. It builds without any problem. Then I download make.exe from the second link on google search (http://www.equation.com/servlet/equation.cmd?fa=make) because it says it is of newer version 4.1 - and it works as well.

So, I don't understand what is the problem on Windows.
Let's assume the problem is that it is too hard to find and download GNU make because Google suggest to search for cmake instead. Ok. Then open VS command line and do the following:

  cd <TBB>\build\vs2010
  msbuild makefile.sln

It is not the very same way Intel builds its binaries, but at least VS projects are shipped and supported along with the sources package of TBB.

**Comment by ocefpaf** [comment]
> What do you mean by "no real way"?

We are looking into adding `MSYS2` on conda-forge and use that for some builds. `cmake` is the preferred way for now only because that is the technology that most Windows experts here are used to.

BTW if you want to send a PR modifying the Windows builds it would be awesome!

Thanks @antalmal for your input! We'll keep you informed as this feedstock evolves.

**Comment by jakirkham** [comment]
To be clear, I'm not the maintainer on the feedstock or a Windows build expert. I'm just summarizing what was decided in the PR that added `tbb` (namely using CMake). The history lives over here ( https://github.com/conda-forge/staged-recipes/pull/533 ). Maybe someone else can better answer your questions. I will cc them here. ( @msarahan @patricksnape )

**Comment by patricksnape** [comment]
This is merely an issue with the fact that forcing the `make` ecosystem onto Windows awkward. Just because the TBB recipe happens to use no other unix utilities doesn't mean this is true in the general case. As @ocefpaf said, hopefully soon we will support a proper `msys2` environment and thus we can effectively support `make` projects on Windows. We would welcome a PR here to remove the CMake build whenever the `msys2` ecosystem is ready 😄

**Comment by antalmal** [comment]
Thanks for quick response! Unfortunately, our previous experience with `msys` (1.0) was negative - it tries too hard to pretend that is unix and it does not work with TBB's makefiles well enough. The problem is because `msys` has `sh.exe` and `make.exe` is configured to run with `SHELL=sh` by default in `msys`. But `sh` has different quoting rules that are incompatible with the ones for `cmd.exe`, that's why it is probably not possible to build cross-Shell makefiles which work in both modes. In particular `$(shell )` command does not work with `msys`. If it would be possible - it is a feature request to TBB team. And I'm not sure if `msys2` has the same problem.

So, it might be a good idea to use `msbuild` instead.

**Comment by anton-malakhov** [comment]
TBB folks just released official support for CMake
https://github.com/01org/tbb/tree/tbb_2017/cmake
@tbbdev

**Comment by jschueller** [comment]
unfortunately their cmake modules only allow to build tbb from a cmake project, not the regular build & install like we do here, so our approach still stands

**Comment by jakirkham** [comment]
Yeah I'm not seeing a `CMakeLists.txt` in there. Am I missing it somewhere @anton-malakhov? It seems like the instructions suggest that we [create our own `CMakeLists.txt`]( https://github.com/01org/tbb/tree/tbb_2018/cmake#tutorials-intel-tbb-integration-using-cmake ). 😕
