### ISSUE TITLE
Move bug_fix version to minor_version, remove bug_fix version

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/tbb-feedstock#31]
Since tbb doesn't put out minor versions we should just have a two number conda version (eg `2018.5`). The bot (and me personally) assume that there is a well behaved map between version and URL. Currently this is not the case, since the calculated URL for `2018.0.5` is the same as `2018.1.5`, which could cause issues.

**Comment by CJ-Wright** [comment]
Attn: @isuruf

**Comment by CJ-Wright** [comment]
Maybe we should put this in docs somewhere?

**Comment by anton-malakhov** [comment]
What's that 'bug_fix' version? do you mean the third component of the version number? Fortunately, it is the plan for 2019 release which simplifies versioning by removing that `.0.` in the middle. But generally speaking, it would not be acceptable solution if we did not have that plan.. because you want to have the same versioning scheme in conda-forge as the official releases and other distributions do. If the official version is described like 2018.0.4, that's what conda-forge should be following.

On the other hand, for sake of the bot, we can artificially complicate the tag name calculation so it can add some garbage for the non-zero value of the unused version components (which will never happen though). Would it work for you?

**Comment by isuruf** [comment]
> On the other hand, for sake of the bot, we can artificially complicate the tag name calculation so it can add some garbage for the non-zero value of the unused version components (which will never happen though). Would it work for you?

That works
